### ISSUE TITLE
It crashes when I try to run it.

### ISSUE THREAD

**Issue by Ahmad45123** [AhmedNasserG/GUC-Grades#17]
```
DevTools listening on ws://127.0.0.1:56647/devtools/browser/03e603fa-3d37-40be-b40d-accb50cc34c5
GUC-Grades.py:267: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  select = Select(browser.find_element_by_xpath('//*[@id="smCrsLst"]'))
Traceback (most recent call last):
  File "GUC-Grades.py", line 267, in <module>
    select = Select(browser.find_element_by_xpath('//*[@id="smCrsLst"]'))
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 520, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1246, in find_element
    'value': value})['value']
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="smCrsLst"]"}
  (Session info: headless chrome=97.0.4692.71)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.19043 x86_64)
```

Windows 10

plz help a poor man

**Comment by Ahmad45123** [comment]
![image](https://user-images.githubusercontent.com/8184424/149194543-a6263ee3-b6df-46b8-a539-fb0e913b78de.png)

**Comment by AhmedNasserG** [comment]
the problem should be solved now try again
